const number = 10;
try {
  number = 20;
} catch (err) {
  console.log(err);
}
console.log(number);
